name: Pull Request

on: [pull_request]

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tiulpin/qodana-action@main
        with: 
          linter: jetbrains/qodana-jvm
          fail-threshold: 1
